const countries = [
    { Country: "Niue", Slug: "niue", ISO2: "NU" },
    { Country: "San Marino", Slug: "san-marino", ISO2: "SM" },
    {
        Country: "Hong Kong, SAR China",
        Slug: "hong-kong-sar-china",
        ISO2: "HK",
    },
    { Country: "Italy", Slug: "italy", ISO2: "IT" },
    { Country: "Nauru", Slug: "nauru", ISO2: "NR" },
    { Country: "Pitcairn", Slug: "pitcairn", ISO2: "PN" },
    { Country: "Serbia", Slug: "serbia", ISO2: "RS" },
    { Country: "Jordan", Slug: "jordan", ISO2: "JO" },
    { Country: "Mauritania", Slug: "mauritania", ISO2: "MR" },
    { Country: "India", Slug: "india", ISO2: "IN" },
    { Country: "Morocco", Slug: "morocco", ISO2: "MA" },
    { Country: "Papua New Guinea", Slug: "papua-new-guinea", ISO2: "PG" },
    { Country: "Brazil", Slug: "brazil", ISO2: "BR" },
    { Country: "Brunei Darussalam", Slug: "brunei", ISO2: "BN" },
    { Country: "Equatorial Guinea", Slug: "equatorial-guinea", ISO2: "GQ" },
    { Country: "Egypt", Slug: "egypt", ISO2: "EG" },
    { Country: "Paraguay", Slug: "paraguay", ISO2: "PY" },
    { Country: "Saint Helena", Slug: "saint-helena", ISO2: "SH" },
    { Country: "Ukraine", Slug: "ukraine", ISO2: "UA" },
    { Country: "Cambodia", Slug: "cambodia", ISO2: "KH" },
    { Country: "Chad", Slug: "chad", ISO2: "TD" },
    { Country: "Jersey", Slug: "jersey", ISO2: "JE" },
    { Country: "Isle of Man", Slug: "isle-of-man", ISO2: "IM" },
    { Country: "Timor-Leste", Slug: "timor-leste", ISO2: "TL" },
    { Country: "Ghana", Slug: "ghana", ISO2: "GH" },
    { Country: "Virgin Islands, US", Slug: "virgin-islands", ISO2: "VI" },
    { Country: "Trinidad and Tobago", Slug: "trinidad-and-tobago", ISO2: "TT" },
    { Country: "Belgium", Slug: "belgium", ISO2: "BE" },
    { Country: "Denmark", Slug: "denmark", ISO2: "DK" },
    { Country: "Gabon", Slug: "gabon", ISO2: "GA" },
    { Country: "Barbados", Slug: "barbados", ISO2: "BB" },
    {
        Country: "Falkland Islands (Malvinas)",
        Slug: "falkland-islands-malvinas",
        ISO2: "FK",
    },
    { Country: "Peru", Slug: "peru", ISO2: "PE" },
    { Country: "French Guiana", Slug: "french-guiana", ISO2: "GF" },
    { Country: "Gibraltar", Slug: "gibraltar", ISO2: "GI" },
    { Country: "Kuwait", Slug: "kuwait", ISO2: "KW" },
    { Country: "Latvia", Slug: "latvia", ISO2: "LV" },
    { Country: "Portugal", Slug: "portugal", ISO2: "PT" },
    { Country: "American Samoa", Slug: "american-samoa", ISO2: "AS" },
    { Country: "Saudi Arabia", Slug: "saudi-arabia", ISO2: "SA" },
    { Country: "Malaysia", Slug: "malaysia", ISO2: "MY" },
    { Country: "Guernsey", Slug: "guernsey", ISO2: "GG" },
    { Country: "Indonesia", Slug: "indonesia", ISO2: "ID" },
    { Country: "Kiribati", Slug: "kiribati", ISO2: "KI" },
    {
        Country: "Bosnia and Herzegovina",
        Slug: "bosnia-and-herzegovina",
        ISO2: "BA",
    },
    { Country: "Fiji", Slug: "fiji", ISO2: "FJ" },
    { Country: "Kenya", Slug: "kenya", ISO2: "KE" },
    { Country: "Korea (North)", Slug: "korea-north", ISO2: "KP" },
    {
        Country: "Sao Tome and Principe",
        Slug: "sao-tome-and-principe",
        ISO2: "ST",
    },
    { Country: "Uruguay", Slug: "uruguay", ISO2: "UY" },
    { Country: "Ecuador", Slug: "ecuador", ISO2: "EC" },
    { Country: "Georgia", Slug: "georgia", ISO2: "GE" },
    { Country: "Marshall Islands", Slug: "marshall-islands", ISO2: "MH" },
    { Country: "Myanmar", Slug: "myanmar", ISO2: "MM" },
    { Country: "Poland", Slug: "poland", ISO2: "PL" },
    { Country: "Aruba", Slug: "aruba", ISO2: "AW" },
    { Country: "Belize", Slug: "belize", ISO2: "BZ" },
    { Country: "Cyprus", Slug: "cyprus", ISO2: "CY" },
    { Country: "Sweden", Slug: "sweden", ISO2: "SE" },
    {
        Country: "Northern Mariana Islands",
        Slug: "northern-mariana-islands",
        ISO2: "MP",
    },
    { Country: "Liechtenstein", Slug: "liechtenstein", ISO2: "LI" },
    { Country: "Malawi", Slug: "malawi", ISO2: "MW" },
    { Country: "Uzbekistan", Slug: "uzbekistan", ISO2: "UZ" },
    { Country: "Antarctica", Slug: "antarctica", ISO2: "AQ" },
    { Country: "Côte d'Ivoire", Slug: "cote-divoire", ISO2: "CI" },
    { Country: "Nigeria", Slug: "nigeria", ISO2: "NG" },
    { Country: "Gambia", Slug: "gambia", ISO2: "GM" },
    { Country: "Iraq", Slug: "iraq", ISO2: "IQ" },
    { Country: "Eritrea", Slug: "eritrea", ISO2: "ER" },
    { Country: "Guatemala", Slug: "guatemala", ISO2: "GT" },
    { Country: "Puerto Rico", Slug: "puerto-rico", ISO2: "PR" },
    {
        Country: "Saint Pierre and Miquelon",
        Slug: "saint-pierre-and-miquelon",
        ISO2: "PM",
    },
    { Country: "Turkey", Slug: "turkey", ISO2: "TR" },
    { Country: "Algeria", Slug: "algeria", ISO2: "DZ" },
    { Country: "Burkina Faso", Slug: "burkina-faso", ISO2: "BF" },
    { Country: "Niger", Slug: "niger", ISO2: "NE" },
    { Country: "Saint-Barthélemy", Slug: "saint-barthélemy", ISO2: "BL" },
    {
        Country: "Wallis and Futuna Islands",
        Slug: "wallis-and-futuna-islands",
        ISO2: "WF",
    },
    { Country: "Belarus", Slug: "belarus", ISO2: "BY" },
    { Country: "Jamaica", Slug: "jamaica", ISO2: "JM" },
    { Country: "Montenegro", Slug: "montenegro", ISO2: "ME" },
    { Country: "Monaco", Slug: "monaco", ISO2: "MC" },
    { Country: "Nepal", Slug: "nepal", ISO2: "NP" },
    { Country: "Guinea-Bissau", Slug: "guinea-bissau", ISO2: "GW" },
    { Country: "Mexico", Slug: "mexico", ISO2: "MX" },
    { Country: "Angola", Slug: "angola", ISO2: "AO" },
    { Country: "Bahrain", Slug: "bahrain", ISO2: "BH" },
    { Country: "Libya", Slug: "libya", ISO2: "LY" },
    { Country: "Lithuania", Slug: "lithuania", ISO2: "LT" },
    { Country: "Mauritius", Slug: "mauritius", ISO2: "MU" },
    { Country: "Moldova", Slug: "moldova", ISO2: "MD" },
    { Country: "Samoa", Slug: "samoa", ISO2: "WS" },
    { Country: "Ireland", Slug: "ireland", ISO2: "IE" },
    { Country: "Slovakia", Slug: "slovakia", ISO2: "SK" },
    { Country: "Switzerland", Slug: "switzerland", ISO2: "CH" },
    { Country: "Luxembourg", Slug: "luxembourg", ISO2: "LU" },
    { Country: "Zimbabwe", Slug: "zimbabwe", ISO2: "ZW" },
    { Country: "Antigua and Barbuda", Slug: "antigua-and-barbuda", ISO2: "AG" },
    { Country: "Cameroon", Slug: "cameroon", ISO2: "CM" },
    {
        Country: "French Southern Territories",
        Slug: "french-southern-territories",
        ISO2: "TF",
    },
    {
        Country: "British Virgin Islands",
        Slug: "british-virgin-islands",
        ISO2: "VG",
    },
    { Country: "Liberia", Slug: "liberia", ISO2: "LR" },
    { Country: "Guinea", Slug: "guinea", ISO2: "GN" },
    {
        Country: "Saint Vincent and Grenadines",
        Slug: "saint-vincent-and-the-grenadines",
        ISO2: "VC",
    },
    { Country: "United Kingdom", Slug: "united-kingdom", ISO2: "GB" },
    {
        Country: "Venezuela (Bolivarian Republic)",
        Slug: "venezuela",
        ISO2: "VE",
    },
    { Country: "Australia", Slug: "australia", ISO2: "AU" },
    { Country: "Lebanon", Slug: "lebanon", ISO2: "LB" },
    { Country: "Seychelles", Slug: "seychelles", ISO2: "SC" },
    { Country: "Palau", Slug: "palau", ISO2: "PW" },
    { Country: "Yemen", Slug: "yemen", ISO2: "YE" },
    { Country: "Bermuda", Slug: "bermuda", ISO2: "BM" },
    { Country: "Botswana", Slug: "botswana", ISO2: "BW" },
    { Country: "Kyrgyzstan", Slug: "kyrgyzstan", ISO2: "KG" },
    { Country: "Christmas Island", Slug: "christmas-island", ISO2: "CX" },
    { Country: "Mongolia", Slug: "mongolia", ISO2: "MN" },
    { Country: "Qatar", Slug: "qatar", ISO2: "QA" },
    { Country: "South Sudan", Slug: "south-sudan", ISO2: "SS" },
    { Country: "Guam", Slug: "guam", ISO2: "GU" },
    { Country: "Hungary", Slug: "hungary", ISO2: "HU" },
    { Country: "Thailand", Slug: "thailand", ISO2: "TH" },
    { Country: "Uganda", Slug: "uganda", ISO2: "UG" },
    { Country: "Guadeloupe", Slug: "guadeloupe", ISO2: "GP" },
    { Country: "Norfolk Island", Slug: "norfolk-island", ISO2: "NF" },
    { Country: "Panama", Slug: "panama", ISO2: "PA" },
    { Country: "Palestinian Territory", Slug: "palestine", ISO2: "PS" },
    { Country: "Greece", Slug: "greece", ISO2: "GR" },
    { Country: "Korea (South)", Slug: "korea-south", ISO2: "KR" },
    { Country: "Mozambique", Slug: "mozambique", ISO2: "MZ" },
    {
        Country: "British Indian Ocean Territory",
        Slug: "british-indian-ocean-territory",
        ISO2: "IO",
    },
    { Country: "France", Slug: "france", ISO2: "FR" },
    {
        Country: "Saint Kitts and Nevis",
        Slug: "saint-kitts-and-nevis",
        ISO2: "KN",
    },
    { Country: "Saint Lucia", Slug: "saint-lucia", ISO2: "LC" },
    { Country: "Suriname", Slug: "suriname", ISO2: "SR" },
    { Country: "ALA Aland Islands", Slug: "ala-aland-islands", ISO2: "AX" },
    { Country: "Argentina", Slug: "argentina", ISO2: "AR" },
    { Country: "Togo", Slug: "togo", ISO2: "TG" },
    { Country: "Maldives", Slug: "maldives", ISO2: "MV" },
    { Country: "Taiwan, Republic of China", Slug: "taiwan", ISO2: "TW" },
    { Country: "Dominica", Slug: "dominica", ISO2: "DM" },
    { Country: "Lesotho", Slug: "lesotho", ISO2: "LS" },
    { Country: "Norway", Slug: "norway", ISO2: "NO" },
    { Country: "Tokelau", Slug: "tokelau", ISO2: "TK" },
    {
        Country: "US Minor Outlying Islands",
        Slug: "us-minor-outlying-islands",
        ISO2: "UM",
    },
    { Country: "Azerbaijan", Slug: "azerbaijan", ISO2: "AZ" },
    { Country: "Cuba", Slug: "cuba", ISO2: "CU" },
    { Country: "Honduras", Slug: "honduras", ISO2: "HN" },
    { Country: "Mali", Slug: "mali", ISO2: "ML" },
    { Country: "Andorra", Slug: "andorra", ISO2: "AD" },
    { Country: "Bulgaria", Slug: "bulgaria", ISO2: "BG" },
    { Country: "Comoros", Slug: "comoros", ISO2: "KM" },
    { Country: "Sierra Leone", Slug: "sierra-leone", ISO2: "SL" },
    { Country: "Tunisia", Slug: "tunisia", ISO2: "TN" },
    { Country: "Iran, Islamic Republic of", Slug: "iran", ISO2: "IR" },
    { Country: "Macao, SAR China", Slug: "macao-sar-china", ISO2: "MO" },
    { Country: "Montserrat", Slug: "montserrat", ISO2: "MS" },
    { Country: "Pakistan", Slug: "pakistan", ISO2: "PK" },
    { Country: "Macedonia, Republic of", Slug: "macedonia", ISO2: "MK" },
    { Country: "Malta", Slug: "malta", ISO2: "MT" },
    { Country: "Namibia", Slug: "namibia", ISO2: "NA" },
    { Country: "Solomon Islands", Slug: "solomon-islands", ISO2: "SB" },
    { Country: "Zambia", Slug: "zambia", ISO2: "ZM" },
    { Country: "Finland", Slug: "finland", ISO2: "FI" },
    { Country: "Japan", Slug: "japan", ISO2: "JP" },
    { Country: "Cayman Islands", Slug: "cayman-islands", ISO2: "KY" },
    { Country: "Congo (Brazzaville)", Slug: "congo-brazzaville", ISO2: "CG" },
    { Country: "Senegal", Slug: "senegal", ISO2: "SN" },
    { Country: "Canada", Slug: "canada", ISO2: "CA" },
    { Country: "Chile", Slug: "chile", ISO2: "CL" },
    { Country: "Grenada", Slug: "grenada", ISO2: "GD" },
    { Country: "Slovenia", Slug: "slovenia", ISO2: "SI" },
    { Country: "Dominican Republic", Slug: "dominican-republic", ISO2: "DO" },
    { Country: "Nicaragua", Slug: "nicaragua", ISO2: "NI" },
    { Country: "Republic of Kosovo", Slug: "kosovo", ISO2: "XK" },
    { Country: "Benin", Slug: "benin", ISO2: "BJ" },
    { Country: "Burundi", Slug: "burundi", ISO2: "BI" },
    { Country: "Mayotte", Slug: "mayotte", ISO2: "YT" },
    { Country: "Sri Lanka", Slug: "sri-lanka", ISO2: "LK" },
    { Country: "Swaziland", Slug: "swaziland", ISO2: "SZ" },
    { Country: "Armenia", Slug: "armenia", ISO2: "AM" },
    { Country: "Colombia", Slug: "colombia", ISO2: "CO" },
    { Country: "Congo (Kinshasa)", Slug: "congo-kinshasa", ISO2: "CD" },
    { Country: "Estonia", Slug: "estonia", ISO2: "EE" },
    { Country: "Bangladesh", Slug: "bangladesh", ISO2: "BD" },
    { Country: "Singapore", Slug: "singapore", ISO2: "SG" },
    { Country: "South Africa", Slug: "south-africa", ISO2: "ZA" },
    { Country: "Tuvalu", Slug: "tuvalu", ISO2: "TV" },
    { Country: "Bouvet Island", Slug: "bouvet-island", ISO2: "BV" },
    { Country: "French Polynesia", Slug: "french-polynesia", ISO2: "PF" },
    {
        Country: "Heard and Mcdonald Islands",
        Slug: "heard-and-mcdonald-islands",
        ISO2: "HM",
    },
    { Country: "Kazakhstan", Slug: "kazakhstan", ISO2: "KZ" },
    { Country: "Anguilla", Slug: "anguilla", ISO2: "AI" },
    { Country: "Czech Republic", Slug: "czech-republic", ISO2: "CZ" },
    { Country: "Germany", Slug: "germany", ISO2: "DE" },
    {
        Country: "Svalbard and Jan Mayen Islands",
        Slug: "svalbard-and-jan-mayen-islands",
        ISO2: "SJ",
    },
    { Country: "Martinique", Slug: "martinique", ISO2: "MQ" },
    { Country: "Spain", Slug: "spain", ISO2: "ES" },
    { Country: "United States of America", Slug: "united-states", ISO2: "US" },
    { Country: "Bolivia", Slug: "bolivia", ISO2: "BO" },
    { Country: "Somalia", Slug: "somalia", ISO2: "SO" },
    { Country: "Rwanda", Slug: "rwanda", ISO2: "RW" },
    {
        Country: "Saint-Martin (French part)",
        Slug: "saint-martin-french-part",
        ISO2: "MF",
    },
    { Country: "Cook Islands", Slug: "cook-islands", ISO2: "CK" },
    { Country: "Croatia", Slug: "croatia", ISO2: "HR" },
    { Country: "China", Slug: "china", ISO2: "CN" },
    { Country: "Ethiopia", Slug: "ethiopia", ISO2: "ET" },
    { Country: "Faroe Islands", Slug: "faroe-islands", ISO2: "FO" },
    { Country: "Iceland", Slug: "iceland", ISO2: "IS" },
    { Country: "Bhutan", Slug: "bhutan", ISO2: "BT" },
    { Country: "El Salvador", Slug: "el-salvador", ISO2: "SV" },
    { Country: "Netherlands", Slug: "netherlands", ISO2: "NL" },
    { Country: "Syrian Arab Republic (Syria)", Slug: "syria", ISO2: "SY" },
    { Country: "Tanzania, United Republic of", Slug: "tanzania", ISO2: "TZ" },
    {
        Country: "Central African Republic",
        Slug: "central-african-republic",
        ISO2: "CF",
    },
    { Country: "Haiti", Slug: "haiti", ISO2: "HT" },
    { Country: "New Caledonia", Slug: "new-caledonia", ISO2: "NC" },
    { Country: "Vanuatu", Slug: "vanuatu", ISO2: "VU" },
    { Country: "Afghanistan", Slug: "afghanistan", ISO2: "AF" },
    { Country: "New Zealand", Slug: "new-zealand", ISO2: "NZ" },
    { Country: "Tajikistan", Slug: "tajikistan", ISO2: "TJ" },
    { Country: "Tonga", Slug: "tonga", ISO2: "TO" },
    { Country: "Turkmenistan", Slug: "turkmenistan", ISO2: "TM" },
    { Country: "Madagascar", Slug: "madagascar", ISO2: "MG" },
    {
        Country: "Micronesia, Federated States of",
        Slug: "micronesia",
        ISO2: "FM",
    },
    { Country: "Israel", Slug: "israel", ISO2: "IL" },
    { Country: "Lao PDR", Slug: "lao-pdr", ISO2: "LA" },
    { Country: "Russian Federation", Slug: "russia", ISO2: "RU" },
    { Country: "Albania", Slug: "albania", ISO2: "AL" },
    { Country: "Bahamas", Slug: "bahamas", ISO2: "BS" },
    { Country: "Djibouti", Slug: "djibouti", ISO2: "DJ" },
    { Country: "Greenland", Slug: "greenland", ISO2: "GL" },
    {
        Country: "Holy See (Vatican City State)",
        Slug: "holy-see-vatican-city-state",
        ISO2: "VA",
    },
    { Country: "Sudan", Slug: "sudan", ISO2: "SD" },
    {
        Country: "Cocos (Keeling) Islands",
        Slug: "cocos-keeling-islands",
        ISO2: "CC",
    },
    { Country: "Costa Rica", Slug: "costa-rica", ISO2: "CR" },
    { Country: "Oman", Slug: "oman", ISO2: "OM" },
    { Country: "Romania", Slug: "romania", ISO2: "RO" },
    {
        Country: "United Arab Emirates",
        Slug: "united-arab-emirates",
        ISO2: "AE",
    },
    { Country: "Viet Nam", Slug: "vietnam", ISO2: "VN" },
    { Country: "Western Sahara", Slug: "western-sahara", ISO2: "EH" },
    { Country: "Austria", Slug: "austria", ISO2: "AT" },
    { Country: "Cape Verde", Slug: "cape-verde", ISO2: "CV" },
    {
        Country: "Netherlands Antilles",
        Slug: "netherlands-antilles",
        ISO2: "AN",
    },
    { Country: "Guyana", Slug: "guyana", ISO2: "GY" },
    { Country: "Réunion", Slug: "réunion", ISO2: "RE" },
    {
        Country: "Turks and Caicos Islands",
        Slug: "turks-and-caicos-islands",
        ISO2: "TC",
    },
    { Country: "Philippines", Slug: "philippines", ISO2: "PH" },
    {
        Country: "South Georgia and the South Sandwich Islands",
        Slug: "south-georgia-and-the-south-sandwich-islands",
        ISO2: "GS",
    },
];

const pop = [
    {
        name: "Afghanistan",
        iso: "AF",
        population: 38041754,
    },
    {
        name: "Albania",
        iso: "AL",
        population: 2880917,
    },
    {
        name: "Algeria",
        iso: "DZ",
        population: 43053054,
    },
    {
        name: "American Samoa",
        iso: "AS",
        population: 55312,
    },
    {
        name: "Andorra",
        iso: "AD",
        population: 77142,
    },
    {
        name: "Angola",
        iso: "AO",
        population: 31825295,
    },
    {
        name: "Anguilla",
        iso: "AI",
        population: 14869,
    },
    {
        name: "Antigua and Barbuda",
        iso: "AG",
        population: 97118,
    },
    {
        name: "Argentina",
        iso: "AR",
        population: 44780677,
    },
    {
        name: "Armenia",
        iso: "AM",
        population: 2957731,
    },
    {
        name: "Aruba",
        iso: "AW",
        population: 106314,
    },
    {
        name: "Australia",
        iso: "AU",
        population: 25203198,
    },
    {
        name: "Austria",
        iso: "AT",
        population: 8955102,
    },
    {
        name: "Azerbaijan",
        iso: "AZ",
        population: 10047718,
    },
    {
        name: "Bahamas",
        iso: "BS",
        population: 389482,
    },
    {
        name: "Bahrain",
        iso: "BH",
        population: 1641172,
    },
    {
        name: "Bangladesh",
        iso: "BD",
        population: 163046161,
    },
    {
        name: "Barbados",
        iso: "BB",
        population: 287025,
    },
    {
        name: "Belarus",
        iso: "BY",
        population: 9452411,
    },
    {
        name: "Belgium",
        iso: "BE",
        population: 11539328,
    },
    {
        name: "Belize",
        iso: "BZ",
        population: 390353,
    },
    {
        name: "Benin",
        iso: "BJ",
        population: 11801151,
    },
    {
        name: "Bermuda",
        iso: "BM",
        population: 62506,
    },
    {
        name: "Bhutan",
        iso: "BT",
        population: 763092,
    },
    {
        name: "Bolivia",
        iso: "BO",
        population: 11513100,
    },
    {
        name: "Bosnia and Herzegovina",
        iso: "BA",
        population: 3301000,
    },
    {
        name: "Botswana",
        iso: "BW",
        population: 2303697,
    },
    {
        name: "Brazil",
        iso: "BR",
        population: 211049527,
    },
    {
        name: "British Virgin Islands",
        iso: "VG",
        population: 30030,
    },
    {
        name: "Brunei",
        iso: "BN",
        population: 433285,
    },
    {
        name: "Bulgaria",
        iso: "BG",
        population: 7000119,
    },
    {
        name: "Burkina Faso",
        iso: "BF",
        population: 20321378,
    },
    {
        name: "Burundi",
        iso: "BI",
        population: 11530580,
    },
    {
        name: "Cambodia",
        iso: "KH",
        population: 16486542,
    },
    {
        name: "Cameroon",
        iso: "CM",
        population: 25876380,
    },
    {
        name: "Canada",
        iso: "CA",
        population: 37411047,
    },
    {
        name: "Cape Verde",
        iso: "CV",
        population: 549935,
    },
    {
        name: "Cayman Islands",
        iso: "KY",
        population: 64948,
    },
    {
        name: "Central African Republic",
        iso: "CF",
        population: 4745185,
    },
    {
        name: "Chad",
        iso: "TD",
        population: 15946876,
    },
    {
        name: "Chile",
        iso: "CL",
        population: 18952038,
    },
    {
        name: "China",
        iso: "CN",
        population: 1433783686,
    },
    {
        name: "Colombia",
        iso: "CO",
        population: 50339443,
    },
    {
        name: "Comoros",
        iso: "KM",
        population: 850886,
    },
    {
        name: "Cook Islands",
        iso: "CK",
        population: 17548,
    },
    {
        name: "Costa Rica",
        iso: "CR",
        population: 5047561,
    },
    {
        name: "Croatia",
        iso: "HR",
        population: 4130304,
    },
    {
        name: "Cuba",
        iso: "CU",
        population: 11333483,
    },
    {
        name: "Curacao",
        iso: "CW",
        population: 163424,
    },
    {
        name: "Cyprus",
        iso: "CY",
        population: 1198575,
    },
    {
        name: "Czech Republic",
        iso: "CZ",
        population: 10689209,
    },
    {
        name: "Denmark",
        iso: "DK",
        population: 5771876,
    },
    {
        name: "Djibouti",
        iso: "DJ",
        population: 973560,
    },
    {
        name: "Dominica",
        iso: "DM",
        population: 71808,
    },
    {
        name: "Dominican Republic",
        iso: "DO",
        population: 10738958,
    },
    {
        name: "DR Congo",
        iso: "CD",
        population: 86790567,
    },
    {
        name: "Ecuador",
        iso: "EC",
        population: 17373662,
    },
    {
        name: "Egypt",
        iso: "EG",
        population: 100388073,
    },
    {
        name: "El Salvador",
        iso: "SV",
        population: 6453553,
    },
    {
        name: "Equatorial Guinea",
        iso: "GQ",
        population: 1355986,
    },
    {
        name: "Eritrea",
        iso: "ER",
        population: 3497117,
    },
    {
        name: "Estonia",
        iso: "EE",
        population: 1325648,
    },
    {
        name: "Ethiopia",
        iso: "ET",
        population: 112078730,
    },
    {
        name: "Falkland Islands",
        iso: "FK",
        population: 3377,
    },
    {
        name: "Faroe Islands",
        iso: "FO",
        population: 48678,
    },
    {
        name: "Fiji",
        iso: "FJ",
        population: 889953,
    },
    {
        name: "Finland",
        iso: "FI",
        population: 5532156,
    },
    {
        name: "France",
        iso: "FR",
        population: 65129728,
    },
    {
        name: "French Guiana",
        iso: "GF",
        population: 290832,
    },
    {
        name: "French Polynesia",
        iso: "PF",
        population: 279287,
    },
    {
        name: "Gabon",
        iso: "GA",
        population: 2172579,
    },
    {
        name: "Gambia",
        iso: "GM",
        population: 2347706,
    },
    {
        name: "Georgia",
        iso: "GE",
        population: 3996765,
    },
    {
        name: "Germany",
        iso: "DE",
        population: 83517045,
    },
    {
        name: "Ghana",
        iso: "GH",
        population: 30417856,
    },
    {
        name: "Gibraltar",
        iso: "GI",
        population: 33701,
    },
    {
        name: "Greece",
        iso: "GR",
        population: 10473455,
    },
    {
        name: "Greenland",
        iso: "GL",
        population: 56672,
    },
    {
        name: "Grenada",
        iso: "GD",
        population: 112003,
    },
    {
        name: "Guadeloupe",
        iso: "GP",
        population: 400056,
    },
    {
        name: "Guam",
        iso: "GU",
        population: 167294,
    },
    {
        name: "Guatemala",
        iso: "GT",
        population: 17581472,
    },
    {
        name: "Guinea",
        iso: "GN",
        population: 12771246,
    },
    {
        name: "Guinea-Bissau",
        iso: "GW",
        population: 1920922,
    },
    {
        name: "Guyana",
        iso: "GY",
        population: 782766,
    },
    {
        name: "Haiti",
        iso: "HT",
        population: 11263077,
    },
    {
        name: "Honduras",
        iso: "HN",
        population: 9746117,
    },
    {
        name: "Hong Kong",
        iso: "HK",
        population: 7436154,
    },
    {
        name: "Hungary",
        iso: "HU",
        population: 9684679,
    },
    {
        name: "Iceland",
        iso: "IS",
        population: 339031,
    },
    {
        name: "India",
        iso: "IN",
        population: 1366417754,
    },
    {
        name: "Indonesia",
        iso: "ID",
        population: 270625568,
    },
    {
        name: "Iran",
        iso: "IR",
        population: 82913906,
    },
    {
        name: "Iraq",
        iso: "IQ",
        population: 39309783,
    },
    {
        name: "Ireland",
        iso: "IE",
        population: 4882495,
    },
    {
        name: "Isle of Man",
        iso: "IM",
        population: 84584,
    },
    {
        name: "Israel",
        iso: "IL",
        population: 8519377,
    },
    {
        name: "Italy",
        iso: "IT",
        population: 60550075,
    },
    {
        name: "Ivory Coast",
        iso: "CI",
        population: 25716544,
    },
    {
        name: "Jamaica",
        iso: "JM",
        population: 2948279,
    },
    {
        name: "Japan",
        iso: "JP",
        population: 126860301,
    },
    {
        name: "Jordan",
        iso: "JO",
        population: 10101694,
    },
    {
        name: "Kazakhstan",
        iso: "KZ",
        population: 18551427,
    },
    {
        name: "Kenya",
        iso: "KE",
        population: 52573973,
    },
    {
        name: "Kiribati",
        iso: "KI",
        population: 117606,
    },
    {
        name: "Kuwait",
        iso: "KW",
        population: 4207083,
    },
    {
        name: "Kyrgyzstan",
        iso: "KG",
        population: 6415850,
    },
    {
        name: "Laos",
        iso: "LA",
        population: 7169455,
    },
    {
        name: "Latvia",
        iso: "LV",
        population: 1906743,
    },
    {
        name: "Lebanon",
        iso: "LB",
        population: 6855713,
    },
    {
        name: "Lesotho",
        iso: "LS",
        population: 2125268,
    },
    {
        name: "Liberia",
        iso: "LR",
        population: 4937374,
    },
    {
        name: "Libya",
        iso: "LY",
        population: 6777452,
    },
    {
        name: "Liechtenstein",
        iso: "LI",
        population: 38019,
    },
    {
        name: "Lithuania",
        iso: "LT",
        population: 2759627,
    },
    {
        name: "Luxembourg",
        iso: "LU",
        population: 615729,
    },
    {
        name: "Macau",
        iso: "MO",
        population: 640445,
    },
    {
        name: "Macedonia",
        iso: "MK",
        population: 2083459,
    },
    {
        name: "Madagascar",
        iso: "MG",
        population: 26969307,
    },
    {
        name: "Malawi",
        iso: "MW",
        population: 18628747,
    },
    {
        name: "Malaysia",
        iso: "MY",
        population: 31949777,
    },
    {
        name: "Maldives",
        iso: "MV",
        population: 530953,
    },
    {
        name: "Mali",
        iso: "ML",
        population: 19658031,
    },
    {
        name: "Malta",
        iso: "MT",
        population: 440372,
    },
    {
        name: "Marshall Islands",
        iso: "MH",
        population: 58791,
    },
    {
        name: "Martinique",
        iso: "MQ",
        population: 375554,
    },
    {
        name: "Mauritania",
        iso: "MR",
        population: 4525696,
    },
    {
        name: "Mauritius",
        iso: "MU",
        population: 1269668,
    },
    {
        name: "Mayotte",
        iso: "YT",
        population: 266150,
    },
    {
        name: "Mexico",
        iso: "MX",
        population: 127575529,
    },
    {
        name: "Micronesia",
        iso: "FM",
        population: 113815,
    },
    {
        name: "Moldova",
        iso: "MD",
        population: 4043263,
    },
    {
        name: "Monaco",
        iso: "MC",
        population: 38964,
    },
    {
        name: "Mongolia",
        iso: "MN",
        population: 3225167,
    },
    {
        name: "Montenegro",
        iso: "ME",
        population: 627987,
    },
    {
        name: "Montserrat",
        iso: "MS",
        population: 4989,
    },
    {
        name: "Morocco",
        iso: "MA",
        population: 36471769,
    },
    {
        name: "Mozambique",
        iso: "MZ",
        population: 30366036,
    },
    {
        name: "Myanmar",
        iso: "MM",
        population: 54045420,
    },
    {
        name: "Namibia",
        iso: "NA",
        population: 2494530,
    },
    {
        name: "Nauru",
        iso: "NR",
        population: 10756,
    },
    {
        name: "Nepal",
        iso: "NP",
        population: 28608710,
    },
    {
        name: "Netherlands",
        iso: "NL",
        population: 17097130,
    },
    {
        name: "New Caledonia",
        iso: "NC",
        population: 282750,
    },
    {
        name: "New Zealand",
        iso: "NZ",
        population: 4783063,
    },
    {
        name: "Nicaragua",
        iso: "NI",
        population: 6545502,
    },
    {
        name: "Niger",
        iso: "NE",
        population: 23310715,
    },
    {
        name: "Nigeria",
        iso: "NG",
        population: 200963599,
    },
    {
        name: "Niue",
        iso: "NU",
        population: 1615,
    },
    {
        name: "North Korea",
        iso: "KP",
        population: 25666161,
    },
    {
        name: "Northern Mariana Islands",
        iso: "MP",
        population: 57216,
    },
    {
        name: "Norway",
        iso: "NO",
        population: 5378857,
    },
    {
        name: "Oman",
        iso: "OM",
        population: 4974986,
    },
    {
        name: "Pakistan",
        iso: "PK",
        population: 216565318,
    },
    {
        name: "Palau",
        iso: "PW",
        population: 18008,
    },
    {
        name: "Palestine",
        iso: "PS",
        population: 4981420,
    },
    {
        name: "Panama",
        iso: "PA",
        population: 4246439,
    },
    {
        name: "Papua New Guinea",
        iso: "PG",
        population: 8776109,
    },
    {
        name: "Paraguay",
        iso: "PY",
        population: 7044636,
    },
    {
        name: "Peru",
        iso: "PE",
        population: 32510453,
    },
    {
        name: "Philippines",
        iso: "PH",
        population: 108116615,
    },
    {
        name: "Poland",
        iso: "PL",
        population: 37887768,
    },
    {
        name: "Portugal",
        iso: "PT",
        population: 10226187,
    },
    {
        name: "Puerto Rico",
        iso: "PR",
        population: 2933408,
    },
    {
        name: "Qatar",
        iso: "QA",
        population: 2832067,
    },
    {
        name: "Republic of the Congo",
        iso: "CG",
        population: 5380508,
    },
    {
        name: "Reunion",
        iso: "RE",
        population: 888927,
    },
    {
        name: "Romania",
        iso: "RO",
        population: 19364557,
    },
    {
        name: "Russia",
        iso: "RU",
        population: 145872256,
    },
    {
        name: "Rwanda",
        iso: "RW",
        population: 12626950,
    },
    {
        name: "Saint Barthélemy",
        iso: "BL",
        population: 9847,
    },
    {
        name: "Saint Kitts and Nevis",
        iso: "KN",
        population: 52823,
    },
    {
        name: "Saint Lucia",
        iso: "LC",
        population: 182790,
    },
    {
        name: "Saint Martin",
        iso: "MF",
        population: 38002,
    },
    {
        name: "Saint Pierre and Miquelon",
        iso: "PM",
        population: 5822,
    },
    {
        name: "Saint Vincent and the Grenadines",
        iso: "VC",
        population: 110589,
    },
    {
        name: "Samoa",
        iso: "WS",
        population: 197097,
    },
    {
        name: "San Marino",
        iso: "SM",
        population: 33860,
    },
    {
        name: "Sao Tome and Principe",
        iso: "ST",
        population: 215056,
    },
    {
        name: "Saudi Arabia",
        iso: "SA",
        population: 34268528,
    },
    {
        name: "Senegal",
        iso: "SN",
        population: 16296364,
    },
    {
        name: "Serbia",
        iso: "RS",
        population: 8772235,
    },
    {
        name: "Seychelles",
        iso: "SC",
        population: 97739,
    },
    {
        name: "Sierra Leone",
        iso: "SL",
        population: 7813215,
    },
    {
        name: "Singapore",
        iso: "SG",
        population: 5804337,
    },
    {
        name: "Sint Maarten",
        iso: "SX",
        population: 42388,
    },
    {
        name: "Slovakia",
        iso: "SK",
        population: 5457013,
    },
    {
        name: "Slovenia",
        iso: "SI",
        population: 2078654,
    },
    {
        name: "Solomon Islands",
        iso: "SB",
        population: 669823,
    },
    {
        name: "Somalia",
        iso: "SO",
        population: 15442905,
    },
    {
        name: "South Africa",
        iso: "ZA",
        population: 58558270,
    },
    {
        name: "South Korea",
        iso: "KR",
        population: 51225308,
    },
    {
        name: "South Sudan",
        iso: "SS",
        population: 11062113,
    },
    {
        name: "Spain",
        iso: "ES",
        population: 46736776,
    },
    {
        name: "Sri Lanka",
        iso: "LK",
        population: 21323733,
    },
    {
        name: "Sudan",
        iso: "SD",
        population: 42813238,
    },
    {
        name: "Suriname",
        iso: "SR",
        population: 581372,
    },
    {
        name: "Swaziland",
        iso: "SZ",
        population: 1148130,
    },
    {
        name: "Sweden",
        iso: "SE",
        population: 10036379,
    },
    {
        name: "Switzerland",
        iso: "CH",
        population: 8591365,
    },
    {
        name: "Syria",
        iso: "SY",
        population: 17070135,
    },
    {
        name: "Taiwan",
        iso: "TW",
        population: 23773876,
    },
    {
        name: "Tajikistan",
        iso: "TJ",
        population: 9321018,
    },
    {
        name: "Tanzania",
        iso: "TZ",
        population: 58005463,
    },
    {
        name: "Thailand",
        iso: "TH",
        population: 69625582,
    },
    {
        name: "Timor-Leste",
        iso: "TL",
        population: 1293119,
    },
    {
        name: "Togo",
        iso: "TG",
        population: 8082366,
    },
    {
        name: "Tokelau",
        iso: "TK",
        population: 1340,
    },
    {
        name: "Tonga",
        iso: "TO",
        population: 104494,
    },
    {
        name: "Trinidad and Tobago",
        iso: "TT",
        population: 1394973,
    },
    {
        name: "Tunisia",
        iso: "TN",
        population: 11694719,
    },
    {
        name: "Turkey",
        iso: "TR",
        population: 83429615,
    },
    {
        name: "Turkmenistan",
        iso: "TM",
        population: 5942089,
    },
    {
        name: "Turks and Caicos Islands",
        iso: "TC",
        population: 38191,
    },
    {
        name: "Tuvalu",
        iso: "TV",
        population: 11646,
    },
    {
        name: "Uganda",
        iso: "UG",
        population: 44269594,
    },
    {
        name: "Ukraine",
        iso: "UA",
        population: 43993638,
    },
    {
        name: "United Arab Emirates",
        iso: "AE",
        population: 9770529,
    },
    {
        name: "United Kingdom",
        iso: "GB",
        population: 67530172,
    },
    {
        name: "United States",
        iso: "US",
        population: 329064917,
    },
    {
        name: "United States Virgin Islands",
        iso: "VI",
        population: 104578,
    },
    {
        name: "Uruguay",
        iso: "UY",
        population: 3461734,
    },
    {
        name: "Uzbekistan",
        iso: "UZ",
        population: 32981716,
    },
    {
        name: "Vanuatu",
        iso: "VU",
        population: 299882,
    },
    {
        name: "Vatican City",
        iso: "VA",
        population: 799,
    },
    {
        name: "Venezuela",
        iso: "VE",
        population: 28515829,
    },
    {
        name: "Vietnam",
        iso: "VN",
        population: 96462106,
    },
    {
        name: "Wallis and Futuna",
        iso: "WF",
        population: 11432,
    },
    {
        name: "Western Sahara",
        iso: "EH",
        population: 582463,
    },
    {
        name: "Yemen",
        iso: "YE",
        population: 29161922,
    },
    {
        name: "Zambia",
        iso: "ZM",
        population: 17861030,
    },
    {
        name: "Zimbabwe",
        iso: "ZW",
        population: 14645468,
    },
];

for (let i = 0; i < countries.length; i++) {
    for (let j = 0; j < pop.length; j++) {
        if (countries[i].ISO2 === pop[j].iso) {
            countries[i].population = pop[j].population;
            break;
        }
    }
}

countries.sort((a, b) => a.Country.localeCompare(b.Country));

export default countries;
